### ISSUE TITLE
Add a map of ftw data

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/fieldsoftheworld.github.io#8]
It'd be great to have a map like https://fiboa.org/map/ that's just the FTW data, like at fieldsofthe.world/map

Initially this should just be the source data files, ideally colored by test / train / val (though that will take a bit of data joining, as the fiboa files are separate from the chip files - https://data.source.coop/kerner-lab/fields-of-the-world/austria/chips_austria.parquet vs https://data.source.coop/kerner-lab/fields-of-the-world-austria/boundaries_austria_2021.parquet)

Eventually it could be nice to show some of the 'output' of FTW models as well, but that can wait till we have more.

**Comment by cholmes** [comment]
Ideally we put the PMTiles for this up on source cooperative. A single one at https://source.coop/kerner-lab/fields-of-the-world seems sufficient, but we could also generate the PMTiles for each field boundary repo.

**Comment by jacobsn** [comment]
Two thoughts:

1. I seem to recall @adeelpu was making some zoomable map visualizations, perhaps in GEE.
2. I also think we had a request out to source.coop folks to see if they were going it possible to render different colors based on attributes.

**Comment by m-mohr** [comment]
- Map for the source data is available: https://fieldsofthe.world/map/
- Also linked to from the website.
- PMTiles file is here for now: https://data.source.coop/kerner-lab/fields-of-the-world/ftw-sources.pmtiles
- Converted/merged using fiboa CLI: https://github.com/fiboa/cli/pull/92
- The file only contains the "standard" fiboa properties (id, geometry, area, perimeter, determination_datetime) + dataset (the name of the source dataset, e.g."austria") + license
