### ISSUE TITLE
Help smaller areas on FTW map show up more?

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/fieldsoftheworld.github.io#9]
The new map looks great!

The nature of the data makes it appear _very_ european-centric. Which it is, but it's not quite as bad as it initially looks.

When zoomed out I don't see India or Rwanda, and I have to look really closely to see Kenya. It'd be great to have those show up a bit more at higher zoom levels. Perhaps a thicker stroke for the outlines (at least when zoomed out)? And/or putting it on carto dark basemap (it still works without any login - https://basemaps.cartocdn.com/rastertiles/dark_nolabels/{z}/{x}/{y}.png
 and https://basemaps.cartocdn.com/rastertiles/dark_only_labels/{z}/{x}/{y}.png)

**Comment by m-mohr** [comment]
Yeah, I think I found a solution that makes small dots based on the zoom level. 
Also added the other basemaps.
Thoughts?

**Comment by cholmes** [comment]
Just randomly did a reload and realized this was improved - looks great!
